# Generated by Django 5.2.5 on 2025-08-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_especialidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('crm', models.CharField(max_length=10)),
                ('especialidade_id', models.ManyToManyField(related_name='especialidade', to='app_especialidade.especialidade')),
            ],
        ),
    ]
